language: r
cache: packages
warnings_are_errors: TRUE

before_install:
  - sudo add-apt-repository -y ppa:cran/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev

script:
- R CMD build .
- travis_wait 45 R CMD check *tar.gz --as-cran
